KangSemin/oneshot

src/main/java/salute/oneshot/domain/ingredient/controller/IngredientController.java, src/main/java/salute/oneshot/domain/ingredient/dto/request/CreateIngrRequestDto.java, src/main/java/salute/oneshot/domain/ingredient/dto/request/CreateIngredientRequestDto.java, src/main/java/salute/oneshot/domain/ingredient/dto/response/IngrResponseDto.java, src/main/java/salute/oneshot/domain/ingredient/dto/response/IngredientResponseDto.java, src/main/java/salute/oneshot/domain/ingredient/dto/service/CreateIngrSDto.java, src/main/java/salute/oneshot/domain/ingredient/dto/service/CreateIngredientSDto.java, src/main/java/salute/oneshot/domain/ingredient/entity/Ingredient.java, src/main/java/salute/oneshot/domain/ingredient/entity/IngredientCategory.java, src/main/java/salute/oneshot/domain/ingredient/service/IngredientService.java
13, 15
재료 등록 api 추가
dto 변환과정 뭔가 뭔간데, 한 번 봐보고 얘기 더 해봐도 될덧
=> feat : 재료 등록 api 추가

src/main/java/salute/oneshot/domain/ingredient/controller/IngredientController.java, src/main/java/salute/oneshot/domain/ingredient/service/IngredientService.java
=> feat : 재료 삭제 api 추가 #ZU7-20

src/main/java/salute/oneshot/domain/ingredient/controller/IngredientController.java
=> fix : 재료 삭제 api 잘못된 controller 반환값 수정

src/main/java/salute/oneshot/domain/ingredient/controller/IngredientController.java, src/main/java/salute/oneshot/domain/ingredient/service/IngredientService.java
=> feat : 재료 조회 api 추가 (단건,전체) #ZU7-18

src/main/java/salute/oneshot/domain/common/dto/entity/BaseEntity.java, src/main/java/salute/oneshot/domain/common/dto/success/ApiResponse.java
=> bugfix: ApiResponse 직렬화 문제 해결  #ZU7-21

.gitignore
=> script:  application.yml 항목 추가 #ZU7-21

build.gradle, src/main/java/salute/oneshot/domain/cocktail/controller/CocktailController.java, src/main/java/salute/oneshot/domain/cocktail/dto/request/CreateCocktailDto.java, src/main/java/salute/oneshot/domain/cocktail/dto/response/CocktailResponseDto.java, src/main/java/salute/oneshot/domain/cocktail/repository/CocktailQueryDslRepository.java, src/main/java/salute/oneshot/domain/cocktail/repository/CocktailRepository.java, src/main/java/salute/oneshot/domain/cocktail/service/CocktailService.java, src/main/java/salute/oneshot/global/config/RedisConfig.java
#ZU7-12, #ZU7-29
칵테일 전체조회기능 추가
=> Feature/cocktail/get all #ZU7-29

docker-compose.yaml
=> script: redis 세팅값 추가 #ZU7-21

src/main/java/salute/oneshot/domain/cocktail/dto/response/CocktailResponseDto.java
=> fix: ãresponseDto ãupdateAt-> modifiedAt 변경 #ZU7-29

Makefile
=> script : add Makefile

src/main/java/salute/oneshot/domain/common/dto/error/ErrorCode.java, src/main/java/salute/oneshot/domain/recipeReview/controller/RecipeReviewController.java, src/main/java/salute/oneshot/domain/recipeReview/dto/request/CreateRecipeReviewRequestDto.java, src/main/java/salute/oneshot/domain/recipeReview/dto/response/RecipeReviewResponseDto.java, src/main/java/salute/oneshot/domain/recipeReview/dto/service/CreateRecipeReviewSDto.java, src/main/java/salute/oneshot/domain/recipeReview/entity/RecipeReview.java, src/main/java/salute/oneshot/domain/recipeReview/service/RecipeReviewService.java
=> feat: 레시피 리뷰 등록 API #ZU7-30

build.gradle, src/main/java/salute/oneshot/domain/common/dto/error/ErrorCode.java, src/main/java/salute/oneshot/domain/common/dto/error/ErrorResponse.java, src/main/java/salute/oneshot/domain/user/entity/UserRole.java, src/main/java/salute/oneshot/global/config/SecurityConfig.java, src/main/java/salute/oneshot/global/security/SecurityConst.java, src/main/java/salute/oneshot/global/security/entity/CustomUserDetails.java, src/main/java/salute/oneshot/global/security/jwt/JwtAccessDeniedHandler.java, src/main/java/salute/oneshot/global/security/jwt/JwtAuthenticationEntryPoint.java, src/main/java/salute/oneshot/global/security/jwt/JwtFilter.java, src/main/java/salute/oneshot/global/security/jwt/JwtProvider.java, src/main/java/salute/oneshot/global/security/service/CustomUserDetailsService.java
=> feat: JWT 토큰 구현 #ZU7-21

src/main/java/salute/oneshot/domain/cocktail/controller/CocktailController.java, src/main/java/salute/oneshot/domain/cocktail/dto/response/CocktailResponseDto.java, src/main/java/salute/oneshot/domain/cocktail/service/CocktailService.java
=> Feature/cocktail/get one recode #ZU7-32

src/main/java/salute/oneshot/domain/cart/controller/CartController.java, src/main/java/salute/oneshot/domain/cart/service/CartService.java
=> feat: 본인 장바구니 비우기 기능 추가 #ZU7-22

src/main/java/salute/oneshot/domain/auth/controller/AuthController.java, src/main/java/salute/oneshot/domain/auth/dto/request/SignInRequestDto.java, src/main/java/salute/oneshot/domain/auth/dto/request/SignUpRequestDto.java, src/main/java/salute/oneshot/domain/auth/dto/response/SignUpResponseDto.java, src/main/java/salute/oneshot/domain/auth/dto/service/SignInSDto.java, src/main/java/salute/oneshot/domain/auth/dto/service/SignUpSDto.java, src/main/java/salute/oneshot/domain/auth/service/AuthService.java, src/main/java/salute/oneshot/domain/common/dto/error/ErrorCode.java, src/main/java/salute/oneshot/domain/user/dto/UserValidationMessage.java, src/main/java/salute/oneshot/domain/user/entity/User.java, src/main/java/salute/oneshot/domain/user/repository/UserRepository.java
=> add: auth create 클래스 추가, 코드 수정 #ZU7-14

src/main/java/salute/oneshot/domain/cart/controller/CartController.java, src/main/java/salute/oneshot/domain/cart/service/CartService.java
=> fix: emptyCart 응답 데이터 제거 #ZU7-22

src/main/java/salute/oneshot/domain/auth/controller/AuthController.java, src/main/java/salute/oneshot/domain/auth/dto/response/SignInResponseDto.java, src/main/java/salute/oneshot/domain/auth/service/AuthService.java, src/main/java/salute/oneshot/domain/user/repository/UserRepository.java
=> feat: Auth 로그인 기능 추가 #ZU7-33

build.gradle, src/main/java/salute/oneshot/global/security/jwt/JwtFilter.java, src/main/java/salute/oneshot/global/security/jwt/JwtProvider.java
- 토큰 검증 예외 처리가 모든 API 경로(api/)에 적용되어 있어 인증이 필요한 요청도 토큰 검증을 건너뛰는 문제 수정
- SecurityContext에 인증 정보가 저장되지 않아 발생하는 CustomUserDetails null 에러 해결
=> fix: JwtFilter 토큰 검증 경로 수정

src/main/java/salute/oneshot/domain/user/controller/UserController.java, src/main/java/salute/oneshot/domain/user/service/UserService.java
=> feat: 로그인한 유저 정보 조회 #ZU7-34

src/main/java/salute/oneshot/domain/auth/service/AuthService.java, src/main/java/salute/oneshot/domain/common/dto/error/ErrorCode.java, src/main/java/salute/oneshot/domain/user/controller/UserController.java, src/main/java/salute/oneshot/domain/user/entity/User.java, src/main/java/salute/oneshot/domain/user/repository/UserRepository.java, src/main/java/salute/oneshot/domain/user/service/UserService.java
37
- 유저 탈퇴 기능 추가 (소프트딜리트)
- 유저 로그인 로직에 소프트딜리트 적용
=> feat: 유저 탈퇴 기능 추가 #ZU7-37

build.gradle, docker-compose.yaml, src/main/java/salute/oneshot/global/security/jwt/JwtProvider.java
=> fix: 시크릿 코드 환경변수 주입방식 변경 #ZU7-21

src/main/java/salute/oneshot/domain/cart/controller/CartController.java, src/main/java/salute/oneshot/domain/cart/dto/request/UpdateCartItemAmountRequestDto.java, src/main/java/salute/oneshot/domain/cart/dto/response/CartItemResponseDto.java, src/main/java/salute/oneshot/domain/cart/dto/response/CartResponseDto.java, src/main/java/salute/oneshot/domain/cart/dto/service/AddCartItemSDto.java, src/main/java/salute/oneshot/domain/cart/dto/service/UpdateItemQuantitySDto.java, src/main/java/salute/oneshot/domain/cart/entity/Cart.java, src/main/java/salute/oneshot/domain/cart/entity/CartItem.java, src/main/java/salute/oneshot/domain/cart/repository/CartItemRepository.java, src/main/java/salute/oneshot/domain/cart/service/CartService.java, src/main/java/salute/oneshot/domain/common/dto/error/ErrorCode.java, src/main/java/salute/oneshot/domain/common/dto/success/ApiResponseMessage.java, src/main/java/salute/oneshot/domain/recipeReview/controller/RecipeReviewController.java
7, 22
- 장바구니 수정 기능 추가(항목 제거, 수량 변경)
- cartItemList -> itemList 이름 변경
- amount -> quantity 이름 변경
=> feat: 장바구니 수정 기능 추가(항목 제거, 수량 변경) #ZU7-22

src/main/java/salute/oneshot/domain/user/dto/UserValidationConst.java, src/main/java/salute/oneshot/domain/user/dto/repuest/UserUpdateRequestDto.java
=> refactor: 유저 정보 수정 벨리데이션 추가 #ZU7-36

src/main/java/salute/oneshot/domain/auth/dto/request/SignInRequestDto.java, src/main/java/salute/oneshot/domain/auth/dto/request/SignUpRequestDto.java, src/main/java/salute/oneshot/domain/user/dto/repuest/UserUpdateRequestDto.java
34
유저 정보 벨리데이션 상수관리 클래스명 변경에 따른 변동사항 적용
=> refactor: 유저 정보 벨리데이션 상수관리 클래스명 변경 #ZU7-34

docker-compose.yaml, src/main/java/salute/oneshot/domain/cocktail/controller/CocktailController.java, src/main/java/salute/oneshot/domain/cocktail/dto/request/IngredientRequestDto.java, src/main/java/salute/oneshot/domain/cocktail/dto/request/UpdateCocktailRequestDto.java, src/main/java/salute/oneshot/domain/cocktail/dto/service/DeleteCocktailSDto.java, src/main/java/salute/oneshot/domain/cocktail/dto/service/UpdateCocktailSDto.java, src/main/java/salute/oneshot/domain/cocktail/entity/Cocktail.java, src/main/java/salute/oneshot/domain/cocktail/service/CocktailService.java
=> Feature/cocktail/update #ZU7-42

docker-compose.yaml, src/main/java/salute/oneshot/domain/cocktail/controller/CocktailController.java, src/main/java/salute/oneshot/domain/cocktail/dto/service/DeleteCocktailSDto.java, src/main/java/salute/oneshot/domain/cocktail/service/CocktailService.java
=> Feature/cocktail/read one #ZU7-32

docker-compose.yaml, src/main/java/salute/oneshot/domain/cocktail/controller/CocktailController.java, src/main/java/salute/oneshot/domain/cocktail/dto/service/DeleteCocktailSDto.java, src/main/java/salute/oneshot/domain/cocktail/repository/CocktailRepository.java, src/main/java/salute/oneshot/domain/cocktail/service/CocktailService.java
=> feat : 칵테일 삭제  api 추가 #ZU7-41

src/main/java/salute/oneshot/domain/ingredient/controller/IngredientController.java, src/main/java/salute/oneshot/domain/ingredient/dto/request/CreateIngrRequestDto.java, src/main/java/salute/oneshot/domain/ingredient/dto/request/UpdateIngrRequestDto.java
=> fix : 열거형을 타입 그대로 받던 이슈 해결

src/main/java/salute/oneshot/domain/recipeReview/controller/RecipeReviewController.java, src/main/java/salute/oneshot/domain/recipeReview/dto/service/CreateRecipeReviewSDto.java, src/main/java/salute/oneshot/domain/recipeReview/dto/service/GetAllRecipeReviewSDto.java, src/main/java/salute/oneshot/domain/recipeReview/entity/RecipeReview.java, src/main/java/salute/oneshot/domain/recipeReview/repository/RecipeReviewRepository.java, src/main/java/salute/oneshot/domain/recipeReview/service/RecipeReviewService.java
=> fix: 레시피 리뷰 목록 조회 수정 #ZU7-38

docker-compose.yaml, src/main/java/salute/oneshot/domain/cocktail/controller/CocktailController.java, src/main/java/salute/oneshot/domain/cocktail/entity/Cocktail.java, src/main/java/salute/oneshot/domain/common/dto/error/ErrorCode.java, src/main/java/salute/oneshot/domain/favorite/controller/FavoriteController.java, src/main/java/salute/oneshot/domain/favorite/dto/response/FavoriteResponseDto.java, src/main/java/salute/oneshot/domain/favorite/dto/service/CreateFavoriteSDto.java, src/main/java/salute/oneshot/domain/favorite/entity/Favorite.java, src/main/java/salute/oneshot/domain/favorite/repository/FavoriteRepository.java, src/main/java/salute/oneshot/domain/favorite/service/FavoriteService.java, src/main/java/salute/oneshot/domain/ingredient/dto/response/IngrResponseDto.java
48(버그픽스), 50(칵테일 즐겨찾기 등록 기능)
bugfix: nullable = false 인데, 기본값이 지정되지 않아 발생한 오류 변경
bugfix: 매핑 경로 오타 변경
bugfix: mysql 포트 변경 (3306)
bugfix: 직렬화 오류 발생 해결
feat: 칵테일 즐겨찾기 등록 기능
=> bugfix: 버그 수정 #ZU7-48 #ZU7-50

src/main/java/salute/oneshot/domain/favorite/controller/FavoriteController.java, src/main/java/salute/oneshot/domain/favorite/dto/response/FavoriteResponseDto.java, src/main/java/salute/oneshot/domain/favorite/entity/Favorite.java
50
- 공백 제거
- recipe_id → cocktail_id
- 매핑 경로 변경 recipes → cocktails
=> refactor: 레시피 즐겨찾기 등록기능 리펙토링 #ZU7-50

src/main/java/salute/oneshot/domain/common/dto/success/ApiResponseMessage.java, src/main/java/salute/oneshot/domain/favorite/controller/FavoriteController.java, src/main/java/salute/oneshot/domain/favorite/dto/request/CreateFavoriteDto.java, src/main/java/salute/oneshot/domain/favorite/dto/response/FavoritePageResponseDto.java, src/main/java/salute/oneshot/domain/favorite/dto/response/FavoriteStatusDto.java, src/main/java/salute/oneshot/domain/favorite/dto/service/FavoriteSDto.java, src/main/java/salute/oneshot/domain/favorite/dto/service/GetFavoritesSDto.java, src/main/java/salute/oneshot/domain/favorite/repository/FavoriteRepository.java, src/main/java/salute/oneshot/domain/favorite/service/FavoriteService.java
=> feat: favorite 조회 기능 추가 #ZU7-51

src/main/java/salute/oneshot/domain/common/dto/success/ApiResponseMessage.java, src/main/java/salute/oneshot/domain/favorite/controller/FavoriteController.java, src/main/java/salute/oneshot/domain/favorite/dto/request/CreateFavoriteDto.java, src/main/java/salute/oneshot/domain/favorite/dto/response/FavoritePageResponseDto.java, src/main/java/salute/oneshot/domain/favorite/dto/response/FavoriteStatusDto.java, src/main/java/salute/oneshot/domain/favorite/dto/response/GetFavoriteStatusDto.java, src/main/java/salute/oneshot/domain/favorite/dto/service/DeleteFavoriteSDto.java, src/main/java/salute/oneshot/domain/favorite/dto/service/FavoriteSDto.java, src/main/java/salute/oneshot/domain/favorite/dto/service/GetFavoritesSDto.java, src/main/java/salute/oneshot/domain/favorite/entity/Favorite.java, src/main/java/salute/oneshot/domain/favorite/repository/FavoriteRepository.java, src/main/java/salute/oneshot/domain/favorite/service/FavoriteService.java, src/main/java/salute/oneshot/global/exception/ForbiddenException.java
=> feat: favorite 삭제 기능 추가 #ZU7-53

src/main/java/salute/oneshot/domain/auth/controller/AuthController.java, src/main/java/salute/oneshot/domain/auth/dto/request/SignInRequestDto.java, src/main/java/salute/oneshot/domain/auth/dto/request/SignUpRequestDto.java, src/main/java/salute/oneshot/domain/auth/dto/service/SignUpSDto.java, src/main/java/salute/oneshot/domain/auth/service/AuthService.java, src/main/java/salute/oneshot/domain/cart/controller/CartController.java, src/main/java/salute/oneshot/domain/cocktail/controller/CocktailController.java, src/main/java/salute/oneshot/domain/common/dto/success/ApiResponseConst.java, src/main/java/salute/oneshot/domain/favorite/controller/FavoriteController.java, src/main/java/salute/oneshot/domain/ingredient/controller/IngredientController.java, src/main/java/salute/oneshot/domain/recipeReview/controller/RecipeReviewController.java, src/main/java/salute/oneshot/domain/user/controller/UserController.java, src/main/java/salute/oneshot/domain/user/dto/repuest/UpdateUserRequestDto.java, src/main/java/salute/oneshot/domain/user/dto/service/UpdateUserSDto.java, src/main/java/salute/oneshot/domain/user/entity/User.java, src/main/java/salute/oneshot/domain/user/service/UserService.java
54
refactor: 유저 수정 방법 변경
refactor: dto 지역변수 명 변경 (풀네임 → 간소화)
refactor: 사용하지 않는 임포트 삭제
refactor: 클래스명 변경 (목적어, 동사 → 동사,목적어)
=> refactor: User, Auth 리펙토링 #ZU7-54

src/main/java/salute/oneshot/domain/recipeReview/controller/RecipeReviewController.java, src/main/java/salute/oneshot/domain/recipeReview/dto/service/CreateRecipeReviewSDto.java, src/main/java/salute/oneshot/domain/recipeReview/service/RecipeReviewService.java
30
레시피 리뷰 등록 URL 수정, CreateRecipeReviewSDto recipeId 수정
=> fix: URL 변경 #ZU7-30

src/main/java/salute/oneshot/domain/common/dto/error/ErrorCode.java, src/main/java/salute/oneshot/domain/recipeReview/controller/RecipeReviewController.java, src/main/java/salute/oneshot/domain/recipeReview/dto/service/DeleteRecipeReviewSDto.java, src/main/java/salute/oneshot/domain/recipeReview/service/RecipeReviewService.java
=> feat: 레시피 리뷰 삭제 API 추가 #ZU7-52

build.gradle, src/main/java/salute/oneshot/domain/cart/entity/Cart.java, src/main/java/salute/oneshot/domain/cart/service/CartService.java, src/main/java/salute/oneshot/domain/common/dto/error/ErrorCode.java, src/main/java/salute/oneshot/domain/common/dto/success/ApiResponseMessage.java, src/main/java/salute/oneshot/domain/order/entity/Order.java, src/main/java/salute/oneshot/domain/order/repository/OrderRepository.java, src/main/java/salute/oneshot/domain/payment/controller/PaymentController.java, src/main/java/salute/oneshot/domain/payment/dto/request/ConfirmPaymentRequestDto.java, src/main/java/salute/oneshot/domain/payment/dto/response/ConfirmPaymentResponseDto.java, src/main/java/salute/oneshot/domain/payment/dto/response/PaymentResponseDto.java, src/main/java/salute/oneshot/domain/payment/dto/service/ConfirmPaymentSDto.java, src/main/java/salute/oneshot/domain/payment/entity/Payment.java, src/main/java/salute/oneshot/domain/payment/repository/PaymentRepository.java, src/main/java/salute/oneshot/domain/payment/service/PaymentService.java
=> feat: 결제 생성 기능 추가 #ZU7-44

src/main/java/salute/oneshot/domain/ingredientReview/controller/IngredientReviewController.java, src/main/java/salute/oneshot/domain/ingredientReview/dto/request/CreateIngrReviewRequestDto.java, src/main/java/salute/oneshot/domain/ingredientReview/dto/response/IngrReviewResponseDto.java, src/main/java/salute/oneshot/domain/ingredientReview/dto/service/CreateIngrReviewSDto.java, src/main/java/salute/oneshot/domain/ingredientReview/dto/service/CreateIngredientReviewSDto.java, src/main/java/salute/oneshot/domain/ingredientReview/entity/IngredientReview.java, src/main/java/salute/oneshot/domain/ingredientReview/service/IngredientReviewService.java, src/main/java/salute/oneshot/domain/recipeReview/controller/RecipeReviewController.java
=> feat: 재료 리뷰 등록 API 추가 #ZU7-63

src/main/java/salute/oneshot/domain/payment/service/PaymentService.java
=> fix: import 에러 수정 #ZU7-44

src/main/java/salute/oneshot/domain/pantry/repository/PantryRepository.java
=> fix : N+1 문제 해결 #ZU7-64

src/main/java/salute/oneshot/domain/pantry/controller/PantryController.java, src/main/java/salute/oneshot/domain/pantry/service/PantryService.java
=> feat : pantry 조회 기능 추가 #ZU7-67

build.gradle, src/main/java/salute/oneshot/domain/address/controller/AddressController.java, src/main/java/salute/oneshot/domain/address/controller/AddressViewController.java, src/main/java/salute/oneshot/domain/address/dto/request/CreateAddressRequestDto.java, src/main/java/salute/oneshot/domain/address/dto/response/AddressResponseDto.java, src/main/java/salute/oneshot/domain/address/dto/service/CreateAddressSdto.java, src/main/java/salute/oneshot/domain/address/entity/Address.java, src/main/java/salute/oneshot/domain/address/repository/AddressRepository.java, src/main/java/salute/oneshot/domain/address/service/AddressService.java, src/main/java/salute/oneshot/global/config/SecurityConfig.java, src/main/java/salute/oneshot/global/security/jwt/JwtFilter.java, src/main/resources/templates/address.html
66
- refactor: 필터링 예외 경로에 주소 등록 view 경로 추가
- add: 주소 입력 view용 html 파일 추가
- script: Thymeleaf 의존성 추가
- feat: 주소 등록 기능 추가
=> feat: 주소 등록 기능 추가 #ZU7-66

src/main/java/salute/oneshot/domain/cart/controller/CartController.java, src/main/java/salute/oneshot/domain/cart/dto/CartValidationConst.java, src/main/java/salute/oneshot/domain/cart/service/CartService.java, src/main/java/salute/oneshot/domain/common/dto/error/ErrorCode.java, src/main/java/salute/oneshot/domain/common/dto/success/ApiResponseConst.java, src/main/java/salute/oneshot/domain/order/entity/Order.java, src/main/java/salute/oneshot/domain/order/entity/OrderStatus.java, src/main/java/salute/oneshot/domain/payment/controller/PaymentController.java, src/main/java/salute/oneshot/domain/payment/dto/request/ConfirmPaymentRequestDto.java, src/main/java/salute/oneshot/domain/payment/dto/response/PaymentResponseDto.java, src/main/java/salute/oneshot/domain/payment/dto/service/ConfirmPaymentSDto.java, src/main/java/salute/oneshot/domain/payment/entity/Payment.java, src/main/java/salute/oneshot/domain/payment/entity/PaymentStatus.java, src/main/java/salute/oneshot/domain/payment/service/PaymentService.java
=> feat: 결제 조회, 승인 기능 추가 #ZU7-44

src/main/java/salute/oneshot/domain/pantry/controller/PantryController.java, src/main/java/salute/oneshot/domain/pantry/dto/service/AddIngrToPantrySDto.java, src/main/java/salute/oneshot/domain/pantry/dto/service/RemoveIngrFromPantrySDto.java, src/main/java/salute/oneshot/domain/pantry/entity/Pantry.java, src/main/java/salute/oneshot/domain/pantry/repository/PantryIngredientRepository.java, src/main/java/salute/oneshot/domain/pantry/repository/PantryRepository.java, src/main/java/salute/oneshot/domain/pantry/service/PantryService.java
=> feat : 팬트리에서 재료 삭제, 팬트리 비우기 api 추가 #ZU7-68 , #ZU7-69

src/main/java/salute/oneshot/domain/address/controller/AddressController.java, src/main/java/salute/oneshot/domain/address/dto/response/AddressPageResponseDto.java, src/main/java/salute/oneshot/domain/address/dto/response/AddressResponseDto.java, src/main/java/salute/oneshot/domain/address/dto/service/AddressSdto.java, src/main/java/salute/oneshot/domain/address/dto/service/GetAddressSDto.java, src/main/java/salute/oneshot/domain/address/dto/service/GetAddressesSDto.java, src/main/java/salute/oneshot/domain/address/entity/Address.java, src/main/java/salute/oneshot/domain/address/repository/AddressRepository.java, src/main/java/salute/oneshot/domain/address/service/AddressService.java, src/main/java/salute/oneshot/domain/common/dto/error/ErrorCode.java, src/main/java/salute/oneshot/domain/common/dto/success/ApiResponseConst.java, src/main/resources/templates/address.html
71
- refactor: 폼 위치 정렬
- refactor: Address 엔티티의 User 참조를 userId로 변경
- refactor: 주소 조회 기능 추가(목록, 단건)
=> feat: 주소 조회 기능 추가 #ZU7-71

src/main/java/salute/oneshot/domain/ingredientReview/controller/IngredientReviewController.java, src/main/java/salute/oneshot/domain/ingredientReview/dto/service/GetMyIngredientReviewSDto.java, src/main/java/salute/oneshot/domain/ingredientReview/repository/IngredientReviewRepository.java, src/main/java/salute/oneshot/domain/ingredientReview/service/IngredientReviewService.java
=> feat: 본인이 작성한 재료 리뷰 조회 API 추가 #ZU7-62

src/main/java/salute/oneshot/domain/pantry/entity/Pantry.java, src/main/java/salute/oneshot/domain/pantry/entity/PantryIngredient.java, src/main/java/salute/oneshot/domain/pantry/repository/PantryIngredientRepository.java, src/main/java/salute/oneshot/domain/pantry/repository/PantryRepository.java, src/main/java/salute/oneshot/domain/pantry/service/PantryService.java
=> refactor : Modifying 옵션으로 캐시 초기화

src/main/java/salute/oneshot/domain/address/controller/AddressController.java, src/main/java/salute/oneshot/domain/address/dto/service/AddressSDto.java, src/main/java/salute/oneshot/domain/address/service/AddressService.java, src/main/java/salute/oneshot/domain/common/dto/success/ApiResponseConst.java
=> feat: 주소 삭제 기능 추가 #ZU7-74

src/main/java/salute/oneshot/domain/common/dto/success/ApiResponseConst.java, src/main/java/salute/oneshot/domain/product/controller/ProductController.java, src/main/java/salute/oneshot/domain/product/dto/request/UpdateProductRequestDto.java, src/main/java/salute/oneshot/domain/product/dto/service/UpdateProductRequestSDto.java, src/main/java/salute/oneshot/domain/product/entity/Product.java, src/main/java/salute/oneshot/domain/product/service/ProductService.java
=> feat: 상품 정보 수정 API 추가 #ZU7-76

src/main/java/salute/oneshot/domain/ingredientReview/controller/IngredientReviewController.java, src/main/java/salute/oneshot/domain/ingredientReview/dto/service/GetAllIngrReviewSDto.java, src/main/java/salute/oneshot/domain/ingredientReview/repository/IngredientReviewRepository.java, src/main/java/salute/oneshot/domain/ingredientReview/service/IngredientReviewService.java
=> feat: 재료 리뷰 목록 조회 API 추가 #ZU7-77

src/main/java/salute/oneshot/domain/address/controller/AddressController.java, src/main/java/salute/oneshot/domain/address/dto/request/CreateAddressRequestDto.java, src/main/java/salute/oneshot/domain/address/dto/request/UpdateAddressRequestDto.java, src/main/java/salute/oneshot/domain/address/dto/service/UpdateAddressSDto.java, src/main/java/salute/oneshot/domain/address/entity/Address.java, src/main/java/salute/oneshot/domain/address/repository/AddressRepository.java, src/main/java/salute/oneshot/domain/address/service/AddressService.java, src/main/java/salute/oneshot/domain/common/dto/error/ErrorCode.java, src/main/resources/templates/address-edit.html, src/main/resources/templates/address-form.html
75
- refactor: 인덱싱 추가, 디폴트값 변경 로직 추가
- refactor: 주소 수정에 기본값 변경 로직 추가
- refactor: Dto 클래스 명 변경
=> refactor: 주소 API 리펙토링 #ZU7-75

src/main/java/salute/oneshot/domain/cocktail/entity/Cocktail.java
=> fix : 연관관계에 의해 삭제가 되지 않던 문제 해결

src/main/java/salute/oneshot/domain/cart/entity/Cart.java, src/main/java/salute/oneshot/domain/common/dto/error/ErrorCode.java, src/main/java/salute/oneshot/domain/common/dto/success/ApiResponseConst.java, src/main/java/salute/oneshot/domain/order/controller/OrderController.java, src/main/java/salute/oneshot/domain/order/dto/request/CreateOrderRequestDto.java, src/main/java/salute/oneshot/domain/order/dto/response/GetOrderResponseDto.java, src/main/java/salute/oneshot/domain/order/dto/response/OrderItemListResponseDto.java, src/main/java/salute/oneshot/domain/order/dto/response/OrderResponseDto.java, src/main/java/salute/oneshot/domain/order/dto/service/CreateOrderSDto.java, src/main/java/salute/oneshot/domain/order/dto/service/GetOrderSDto.java, src/main/java/salute/oneshot/domain/order/entity/Order.java, src/main/java/salute/oneshot/domain/order/entity/OrderItem.java, src/main/java/salute/oneshot/domain/order/service/OrderService.java, src/main/java/salute/oneshot/domain/product/service/ProductService.java
80, 81
주문 생성, 주문 단 건 수정 API 추가
=> feat: 주문 생성, 주문 단 건 수정 API 추가 #ZU7-80, #ZU7-81

.github/workflows/github-actions.yml, docker-compose-prod.yaml
7, 89
- chord: Action에 Gradle build 캐싱 추가
- AWS 배포용 docker-compose-prod.yaml 파일 추가
=> chore: Action에 Gradle build 캐싱 추가 #ZU7-89

src/main/java/salute/oneshot/domain/order/controller/OrderController.java, src/main/java/salute/oneshot/domain/order/dto/response/GetOrderResponseDto.java, src/main/java/salute/oneshot/domain/order/dto/response/OrderItemListResponseDto.java, src/main/java/salute/oneshot/domain/order/dto/response/OrderResponseDto.java, src/main/java/salute/oneshot/domain/order/dto/service/CreateOrderSDto.java, src/main/java/salute/oneshot/domain/order/dto/service/GetAllOrderSDto.java, src/main/java/salute/oneshot/domain/order/dto/service/GetOrderSDto.java, src/main/java/salute/oneshot/domain/order/repository/OrderRepository.java, src/main/java/salute/oneshot/domain/order/service/OrderService.java, src/main/java/salute/oneshot/domain/product/dto/response/ProductResponseDto.java
=> feat: 주문 전체 조회 API 추가 #ZU7-82

src/main/java/salute/oneshot/domain/recipeReview/dto/request/CreateRecipeReviewRequestDto.java, src/main/java/salute/oneshot/domain/recipeReview/dto/request/UpdateRecipeRequestDto.java, src/main/java/salute/oneshot/domain/recipeReview/dto/response/CocktailResponseDto.java, src/main/java/salute/oneshot/domain/recipeReview/dto/response/RecipeReviewResponseDto.java, src/main/java/salute/oneshot/domain/recipeReview/dto/response/UserResponseDto.java, src/main/java/salute/oneshot/domain/recipeReview/dto/service/CreateRecipeReviewSDto.java, src/main/java/salute/oneshot/domain/recipeReview/dto/service/DeleteRecipeReviewSDto.java, src/main/java/salute/oneshot/domain/recipeReview/dto/service/GetAllRecipeReviewSDto.java, src/main/java/salute/oneshot/domain/recipeReview/dto/service/GetMyRecipeReviewSDto.java, src/main/java/salute/oneshot/domain/recipeReview/dto/service/UpdateRecipeReviewSDto.java, src/main/java/salute/oneshot/domain/recipeReview/service/RecipeReviewService.java
55, 62, 77
RecipeReviewRequestDto에 유저, 칵테일 정보 추가
=> refactor: RecipeReviewRequestDto에 유저, 칵테일 정보 추가 #ZU7-55 , #ZU7-52, #ZU7-77

src/main/java/salute/oneshot/domain/common/dto/error/ErrorCode.java, src/main/java/salute/oneshot/domain/common/dto/success/ApiResponseConst.java, src/main/java/salute/oneshot/domain/shipping/controller/ShippingController.java, src/main/java/salute/oneshot/domain/shipping/dto/request/ShippingRequestDto.java, src/main/java/salute/oneshot/domain/shipping/dto/response/CreateShippingResponseDto.java, src/main/java/salute/oneshot/domain/shipping/dto/response/ShippingResponseDto.java, src/main/java/salute/oneshot/domain/shipping/dto/service/ShippingSDto.java, src/main/java/salute/oneshot/domain/shipping/entity/Shipping.java, src/main/java/salute/oneshot/domain/shipping/entity/ShippingStatus.java, src/main/java/salute/oneshot/domain/shipping/enums/CourierCompany.java, src/main/java/salute/oneshot/domain/shipping/repository/ShippingRepository.java, src/main/java/salute/oneshot/domain/shipping/service/ShippingService.java
=> feat: 배송정보 등록 기능 추가 #ZU7-91

src/main/java/salute/oneshot/domain/cocktail/dto/request/CreateCocktailRequestDto.java, src/main/java/salute/oneshot/domain/cocktail/dto/request/SearchCocktailByIngrsReqDto.java, src/main/java/salute/oneshot/domain/cocktail/dto/request/UpdateCocktailRequestDto.java
=> refactor : dto 생성자에 접근제어자 추가

src/main/java/salute/oneshot/domain/ingredientReview/dto/response/IngrReviewResponseDto.java, src/main/java/salute/oneshot/domain/ingredientReview/dto/response/IngredientResponseDto.java, src/main/java/salute/oneshot/domain/ingredientReview/dto/response/UserResponseDto.java, src/main/java/salute/oneshot/domain/ingredientReview/service/IngredientReviewService.java
31, 38, 60
IngrReviewRequestDto에 유저, 재료 정보 추가
=> refactor: IngrReviewRequestDto에 유저, 재료 정보 추가 #ZU7-31, #ZU7-38, #ZU7-60, 

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/github-actions.yml
89
- docker-compose-prod.yml 파일 scp를 통해 서버로 전송 후 dockerhub를 이용한 배포
- ci.yml, cd.yml로 분리
=> chore: 자동 배포를 위한 cd action 추가 #ZU7-89

src/main/java/salute/oneshot/domain/cocktail/repository/CocktailQueryDslRepositoryImpl.java
=> 쿼리 에러 수정 #ZU7-43

.github/workflows/cd.yml
95
- chore: scp action에서 password -> key로 속성 변경
=> chore: scp action에서 password -> key로 속성 변경 #ZU7-95

.github/workflows/cd.yml
10, 95
- chore: docker-compose 옵션 위치 변경, 확장자 yml -> yaml 변경
=> chore: docker-compose 옵션 위치 변경 #ZU7-95

src/main/java/salute/oneshot/domain/common/facade/OrderPaymentFacade.java, src/main/java/salute/oneshot/domain/order/controller/OrderController.java, src/main/java/salute/oneshot/domain/order/service/OrderService.java, src/main/java/salute/oneshot/domain/payment/controller/PaymentController.java, src/main/java/salute/oneshot/domain/payment/controller/PaymentViewController.java
95
- refactor: OrderService와 PaymentService를 Facade 패턴으로 통합
=> refactor: OrderService와 PaymentService를 Facade 패턴으로 통합 #ZU7-95

.github/workflows/cd.yml, .github/workflows/ci.yml
89
-[fix: ci.yml에 develop_v2 브랜치 추가](https://github.com/KangSemin/oneshot/commit/29c35b0757fa46dad20d2295f620c40866a35d7f)
=> Chore/action #ZU7-89

src/main/java/salute/oneshot/aplication/SuperAdminInitializer.java, src/main/java/salute/oneshot/domain/common/dto/error/ErrorCode.java, src/main/java/salute/oneshot/domain/common/dto/success/ApiResponseConst.java, src/main/java/salute/oneshot/domain/user/controller/SuperAdminUserController.java, src/main/java/salute/oneshot/domain/user/dto/repuest/UpdateRoleRequestDto.java, src/main/java/salute/oneshot/domain/user/dto/response/UserRoleResponseDto.java, src/main/java/salute/oneshot/domain/user/dto/service/UpdateRoleSDto.java, src/main/java/salute/oneshot/domain/user/entity/User.java, src/main/java/salute/oneshot/domain/user/entity/UserRole.java, src/main/java/salute/oneshot/domain/user/repository/UserRepository.java, src/main/java/salute/oneshot/domain/user/service/UserService.java
=> feat: SuperAdmin 권한 생성, 유저 권한 변경 추가 #ZU7-104

src/main/java/salute/oneshot/domain/auth/controller/AuthController.java, src/main/java/salute/oneshot/domain/auth/repository/RedisRefreshTokenRepository.java, src/main/java/salute/oneshot/domain/auth/service/AuthService.java, src/main/java/salute/oneshot/domain/user/dto/response/UserRoleResponseDto.java, src/main/java/salute/oneshot/domain/user/dto/service/UpdateRoleSDto.java, src/main/java/salute/oneshot/domain/user/entity/User.java, src/main/java/salute/oneshot/domain/user/entity/UserRole.java, src/main/java/salute/oneshot/domain/user/service/UserService.java, src/main/java/salute/oneshot/global/config/RedisConfig.java, src/main/java/salute/oneshot/global/security/entity/CustomUserDetails.java, src/main/java/salute/oneshot/global/security/jwt/JwtAccessDeniedHandler.java, src/main/java/salute/oneshot/global/security/jwt/JwtFilter.java, src/main/java/salute/oneshot/global/security/jwt/JwtProvider.java, src/main/java/salute/oneshot/global/security/service/CustomUserDetailsService.java
=> refactor: 코드 리펙토링 #ZU7-105

src/main/java/salute/oneshot/domain/cocktail/service/CocktailSchedule.java
=> refactor: 로그 삭제

build.gradle, src/main/java/salute/oneshot/OneshotApplication.java, src/main/java/salute/oneshot/domain/common/facade/OrderPaymentFacade.java, src/main/java/salute/oneshot/domain/order/dto/response/GetOrderDetailsResponseDto.java, src/main/java/salute/oneshot/domain/order/entity/OrderStatus.java, src/main/java/salute/oneshot/domain/order/repository/OrderRepository.java, src/main/java/salute/oneshot/domain/order/service/OrderService.java, src/main/java/salute/oneshot/domain/payment/dto/feign/TossConfirmPaymentRequestDto.java, src/main/java/salute/oneshot/domain/payment/dto/request/ConfirmPaymentRequestDto.java, src/main/java/salute/oneshot/domain/payment/dto/response/PaymentResponseDto.java, src/main/java/salute/oneshot/domain/payment/dto/service/ConfirmPaymentSDto.java, src/main/java/salute/oneshot/domain/payment/entity/Payment.java, src/main/java/salute/oneshot/domain/payment/repository/PaymentRepository.java, src/main/java/salute/oneshot/domain/payment/service/PaymentService.java
95
- refactor: 트랜잭션 분리, 재시도 로직 적용
=> refactor: 트랜잭션 분리, 재시도 로직 적용 #ZU7-95

build.gradle, docker-compose.yaml, src/main/java/salute/oneshot/domain/ingredient/controller/IngredientController.java, src/main/java/salute/oneshot/domain/ingredient/entity/IngredientDocument.java, src/main/java/salute/oneshot/domain/ingredient/service/IngredientService.java, src/main/java/salute/oneshot/global/config/ElasticSearchConfig.java
=> 객체 생성시 엘라스틱 저장 #ZU7-96 #ZU7-107

src/main/java/salute/oneshot/domain/ingredient/controller/IngredientController.java, src/main/java/salute/oneshot/domain/ingredient/entity/IngredientDocument.java, src/main/java/salute/oneshot/domain/ingredient/service/IngredientService.java
=>  객체 정보 수정 엘라스틱에 반영 #ZU7-96 #ZU7-108

src/main/java/salute/oneshot/domain/ingredient/controller/IngredientController.java, src/main/java/salute/oneshot/domain/ingredient/service/IngredientService.java
=> 엘라스틱에서 삭제 #ZU7-96 #ZU7-109

src/main/java/salute/oneshot/domain/order/dto/response/GetOrderDetailsResponseDto.java, src/main/java/salute/oneshot/domain/payment/entity/Payment.java, src/main/java/salute/oneshot/domain/payment/util/PaymentErrorDecoder.java
=> chore: 테이블명 payments로 변경 #ZU7-95

src/main/java/salute/oneshot/domain/cocktail/dto/request/CreateCocktailRequestDto.java, src/main/java/salute/oneshot/domain/cocktail/dto/request/UpdateCocktailRequestDto.java, src/main/java/salute/oneshot/domain/cocktail/entity/CocktailDocument.java, src/main/java/salute/oneshot/domain/cocktail/service/CocktailService.java
엘라스틱 서치의 도큐먼트도 함께 수정되도록 변경
#ZU7-106, #ZU7-111
=> fix : 칵테일 수정 로직 변경 #ZU7-106, #ZU7-111

src/main/java/salute/oneshot/domain/cocktail/controller/CocktailController.java, src/main/java/salute/oneshot/domain/cocktail/dto/service/CreateCocktailSDto.java, src/main/java/salute/oneshot/domain/cocktail/dto/service/DeleteCocktailSDto.java, src/main/java/salute/oneshot/domain/cocktail/service/CocktailService.java
칵테일이 삭제될 때 엘라스틱 서치 도큐먼트도 함께 삭제 되도록 수정
#ZU7-106, #ZU7-112
=> fix : 칵테일 삭제 로직 수정 #ZU7-106, #ZU7-112

build.gradle, src/main/java/salute/oneshot/domain/chat/controller/ChatController.java, src/main/java/salute/oneshot/domain/chat/controller/ChatViewController.java, src/main/java/salute/oneshot/domain/chat/dto/response/FindChatResponseDto.java, src/main/java/salute/oneshot/domain/chat/dto/response/MessageResponseDto.java, src/main/java/salute/oneshot/domain/chat/service/ChatService.java, src/main/java/salute/oneshot/global/config/RedisConfig.java, src/main/java/salute/oneshot/global/config/SecurityWebSocketConfig.java, src/main/java/salute/oneshot/global/config/WebSocketConfiguration.java, src/main/resources/templates/admin-chat.html, src/main/resources/templates/chat.html
118
feat: 채팅 로그 레디스에 저장/조회 기능 추가
=> feat: 채팅 로그 레디스에 저장/조회 기능 추가 #ZU7-118

src/main/java/salute/oneshot/domain/banner/controller/AdminBannerController.java, src/main/java/salute/oneshot/domain/banner/controller/BannerController.java, src/main/java/salute/oneshot/domain/banner/dto/request/BannerRequestDto.java, src/main/java/salute/oneshot/domain/banner/dto/response/BannerPageResponseDto.java, src/main/java/salute/oneshot/domain/banner/dto/response/BannerResponseDto.java, src/main/java/salute/oneshot/domain/banner/dto/service/BannerSDto.java, src/main/java/salute/oneshot/domain/banner/dto/service/GetBannersSDto.java, src/main/java/salute/oneshot/domain/banner/dto/service/UpdateBannerSDto.java, src/main/java/salute/oneshot/domain/banner/entity/Banner.java, src/main/java/salute/oneshot/domain/banner/repository/BannerRepository.java, src/main/java/salute/oneshot/domain/banner/service/BannerService.java, src/main/java/salute/oneshot/domain/common/dto/error/ErrorCode.java, src/main/java/salute/oneshot/domain/common/dto/success/ApiResponseConst.java, src/main/java/salute/oneshot/global/util/DateTimeUtil.java
=> feat: 배너 CRUD #ZU7-115

.github/workflows/ci.yml
=> fix: 브랜치 명에 맞게 변경 #ZU7-89

src/main/java/salute/oneshot/domain/banner/controller/AdminBannerController.java, src/main/java/salute/oneshot/domain/banner/dto/service/BannerSDto.java, src/main/java/salute/oneshot/domain/banner/dto/service/UpdateBannerSDto.java, src/main/java/salute/oneshot/domain/banner/entity/Banner.java
=> refactor: banner 리팩토링 #ZU7-115

src/main/java/salute/oneshot/domain/coupon/controller/AdminCouponController.java, src/main/java/salute/oneshot/domain/coupon/dto/request/CpnRequestDto.java, src/main/java/salute/oneshot/domain/coupon/dto/response/CpnBriefResponseDto.java, src/main/java/salute/oneshot/domain/coupon/dto/service/CreateCpnSDto.java, src/main/java/salute/oneshot/domain/coupon/entity/Coupon.java, src/main/java/salute/oneshot/domain/coupon/repository/CouponRepository.java, src/main/java/salute/oneshot/domain/coupon/service/CouponService.java, src/main/java/salute/oneshot/domain/event/entity/Event.java
=> feat: 쿠폰 생성 기능 추가 #ZU7-116

src/main/java/salute/oneshot/domain/auth/controller/AuthViewController.java
=> feat: auth 로그인 웹뷰 추가

Makefile, src/main/java/salute/oneshot/domain/chat/controller/ChatController.java, src/main/java/salute/oneshot/domain/chat/controller/ChatViewController.java, src/main/java/salute/oneshot/domain/chat/util/CustomHandshakeHandler.java, src/main/java/salute/oneshot/domain/chat/util/StompPrincipal.java, src/main/java/salute/oneshot/domain/payment/controller/PaymentViewController.java, src/main/java/salute/oneshot/global/config/SecurityConfig.java, src/main/java/salute/oneshot/global/config/WebSocketConfig.java, src/main/java/salute/oneshot/global/config/WebSocketSecurityConfig.java, src/main/resources/templates/admin-chat.html, src/main/resources/templates/chat.html, src/main/resources/templates/payment/fail.html, src/main/resources/templates/payment/success.html, src/main/resources/templates/payment/toss-payment.html
=> fix: TossPayment 관련 CSP 설정 변경 #ZU7-95

Dockerfile, docker-compose.yaml, src/main/java/salute/oneshot/domain/cocktail/controller/CocktailController.java, src/main/java/salute/oneshot/domain/cocktail/entity/CocktailDocument.java, src/main/java/salute/oneshot/domain/cocktail/repository/CocktailRepository.java, src/main/java/salute/oneshot/domain/cocktail/service/CocktailService.java, src/main/resources/elasticsearch/cocktail/cocktail-settings.json
=> refactor : 재료 기반 칵테일 검색에 엘라스틱 서치 적용 #ZU7-106 ,#ZU7-114

src/main/java/salute/oneshot/domain/coupon/controller/AdminCouponController.java, src/main/java/salute/oneshot/domain/coupon/repository/CouponRepository.java, src/main/java/salute/oneshot/domain/coupon/service/CouponService.java
=> feat: 쿠폰 삭제 기능 추가 #ZU7-121

src/main/java/salute/oneshot/domain/coupon/controller/AdminCouponController.java, src/main/java/salute/oneshot/domain/coupon/controller/CouponController.java, src/main/java/salute/oneshot/domain/coupon/entity/UserCoupon.java, src/main/java/salute/oneshot/domain/coupon/entity/UserCouponStatus.java, src/main/java/salute/oneshot/domain/coupon/repository/CouponRepository.java, src/main/java/salute/oneshot/domain/coupon/repository/UserCouponRepository.java, src/main/java/salute/oneshot/domain/coupon/service/CouponService.java, src/main/java/salute/oneshot/domain/event/entity/Event.java, src/main/java/salute/oneshot/domain/event/entity/EventStatus.java, src/main/java/salute/oneshot/domain/event/entity/FreeEventWinner.java, src/main/java/salute/oneshot/domain/event/entity/VoteEventCandidate.java, src/main/java/salute/oneshot/domain/event/repository/EventRepository.java, src/main/java/salute/oneshot/domain/event/repository/FreeEventWinnerRepository.java
=> feat: 유저 쿠폰 등록, 수정 API #ZU7-126

src/main/java/salute/oneshot/domain/coupon/controller/AdminCouponController.java, src/main/java/salute/oneshot/domain/coupon/controller/CouponController.java, src/main/java/salute/oneshot/domain/coupon/repository/CouponRepository.java, src/main/java/salute/oneshot/domain/coupon/repository/UserCouponRepository.java, src/main/java/salute/oneshot/domain/coupon/service/CouponService.java
=> feat: 쿠폰 조회기능 추가 #ZU7-127

src/main/java/salute/oneshot/domain/cocktail/controller/CocktailController.java, src/main/java/salute/oneshot/domain/cocktail/dto/service/findCocktailSDto.java, src/main/java/salute/oneshot/domain/cocktail/entity/CocktailDocument.java, src/main/java/salute/oneshot/domain/cocktail/service/CocktailSchedule.java, src/main/java/salute/oneshot/domain/cocktail/service/CocktailService.java, src/main/java/salute/oneshot/domain/ingredient/service/IngredientService.java, src/main/resources/analysis/synonyms.txt, src/main/resources/elasticsearch/cocktail/cocktail-settings.json, src/main/resources/elasticsearch/ingredient/ingredient-settings.json
=> 칵테일 조건 검색 수 #ZU7-106 #ZU7-113

src/main/java/salute/oneshot/domain/coupon/repository/UserCouponRepository.java, src/main/java/salute/oneshot/domain/coupon/service/CouponScheduler.java
128
매일밤 자정에 endTime을 체크하면서 EXPIRED상태로 전환하는 스케쥴러
=> feat: 스케쥴러 추가 (기간만료된 쿠폰 삭제) #ZU7-128

src/main/java/salute/oneshot/domain/cocktail/controller/CocktailController.java, src/main/java/salute/oneshot/domain/cocktail/dto/service/SearchCocktailSDto.java, src/main/java/salute/oneshot/domain/cocktail/service/CocktailService.java, src/main/java/salute/oneshot/global/config/ElasticSearchConfig.java
=> refactor : 코트 리팩터링 및 RecipeType에 따른 필터링 기능 추가

src/main/java/salute/oneshot/domain/chat/controller/ChatController.java, src/main/java/salute/oneshot/domain/chat/controller/ChatStompController.java, src/main/java/salute/oneshot/domain/chat/controller/ChatViewController.java, src/main/java/salute/oneshot/domain/chat/dto/response/ChatPreviewResponseDto.java, src/main/java/salute/oneshot/domain/chat/dto/response/FindChatsResponseDto.java, src/main/java/salute/oneshot/domain/chat/service/ChatService.java, src/main/java/salute/oneshot/domain/chat/util/CustomHandshakeHandler.java, src/main/java/salute/oneshot/domain/cocktail/service/CocktailService.java, src/main/java/salute/oneshot/global/config/SecurityConfig.java, src/main/resources/templates/chat/admin-chat-list.html, src/main/resources/templates/chat/admin-chat.html, src/main/resources/templates/chat/chat.html, src/main/resources/templates/payment/success.html
=> feat: add chat list view for admin #ZU7-118

src/main/java/salute/oneshot/domain/chat/controller/ChatController.java, src/main/java/salute/oneshot/domain/chat/controller/ChatStompController.java, src/main/java/salute/oneshot/domain/chat/controller/ChatViewController.java, src/main/java/salute/oneshot/domain/chat/dto/response/MessageResponseDto.java, src/main/java/salute/oneshot/domain/chat/service/ChatService.java, src/main/resources/templates/chat/admin-chat-list.html, src/main/resources/templates/chat/admin-chat.html, src/main/resources/templates/chat/chat.html
=> fix: 관리자 채팅창에서 다른 채팅창의 메시지도 오던 버그 픽스 #ZU7-118

src/main/java/salute/oneshot/global/config/SecurityConfig.java, src/main/java/salute/oneshot/global/security/SecurityConst.java
=> refactor: 시큐리티 CSP 설정 상수화 #ZU7-135

src/main/java/salute/oneshot/domain/coupon/service/CouponScheduler.java
=> refactor: cron 주석 추가 #ZU7-135

src/main/java/salute/oneshot/domain/cart/controller/CartController.java, src/main/java/salute/oneshot/domain/cart/dto/response/CartItemResponseDto.java, src/main/java/salute/oneshot/domain/cart/service/CartService.java, src/main/java/salute/oneshot/domain/chat/controller/ChatController.java, src/main/java/salute/oneshot/domain/chat/controller/ChatViewController.java, src/main/java/salute/oneshot/domain/chat/dto/response/FindChatListResponseDto.java, src/main/java/salute/oneshot/domain/chat/service/ChatService.java, src/main/java/salute/oneshot/domain/common/dto/error/ErrorCode.java, src/main/java/salute/oneshot/domain/common/dto/success/ApiResponseConst.java, src/main/java/salute/oneshot/domain/payment/controller/PaymentController.java, src/main/java/salute/oneshot/domain/payment/controller/PaymentViewController.java
10
- style: DTO 이름, DTO 내의 필드 변수 이름 수정
- style: 컨트롤러에서 메소드의 url 매핑의 겹치는 부분 클래스의 매핑으로 옮김
- fix: CartContorller - 잘못된 에러 메시지 수정
- fix: 장바구니 추가 시 재고 검증 로직 추가
- style: ChatController 메소드 이름 변경
- style: ChatViewController 메소드 이름, 순서 변경
=> rename: 컨벤션 혹은 가독성을 위한 코드 수정 #ZU7-10

build.gradle, src/main/java/salute/oneshot/domain/auth/controller/AuthController.java, src/main/java/salute/oneshot/domain/auth/entity/OAuthProvider.java, src/main/java/salute/oneshot/domain/auth/entity/SocialUser.java, src/main/java/salute/oneshot/domain/auth/handler/OAuth2FailureHandler.java, src/main/java/salute/oneshot/domain/auth/handler/OAuth2SuccessHandler.java, src/main/java/salute/oneshot/domain/auth/model/GoogleUser.java, src/main/java/salute/oneshot/domain/auth/model/NaverUser.java, src/main/java/salute/oneshot/domain/auth/model/OAuth2ProviderUser.java, src/main/java/salute/oneshot/domain/auth/model/ProviderUser.java, src/main/java/salute/oneshot/domain/auth/repository/SocialUserRepository.java, src/main/java/salute/oneshot/domain/auth/service/CustomOAuth2UserService.java, src/main/java/salute/oneshot/domain/auth/service/DefaultCustomOAuth2User.java, src/main/java/salute/oneshot/domain/common/dto/error/ErrorCode.java, src/main/java/salute/oneshot/domain/user/entity/User.java, src/main/java/salute/oneshot/domain/user/repository/UserRepository.java, src/main/java/salute/oneshot/global/config/SecurityConfig.java, src/main/java/salute/oneshot/global/security/SecurityConst.java, src/main/resources/templates/auth/login.html
136
http://localhost:8080/auth/login
위 경로에서 테스트 가능합니다.
쿠키로 accessToken이 들어가요.
=> feat: 소셜로그인 기능 추가 #ZU7-136

build.gradle, src/main/java/salute/oneshot/dummyGenerator/CSVGenerator.java, src/main/java/salute/oneshot/dummyGenerator/UserDummyGenerator.java
=> feature : 유저 더미 데이터 생성 기능 추가

src/main/java/salute/oneshot/domain/event/controller/AdminEventController.java, src/main/java/salute/oneshot/domain/event/dto/request/EventRequestDto.java, src/main/java/salute/oneshot/domain/event/dto/service/CreateEventSDto.java, src/main/java/salute/oneshot/domain/event/dto/service/UpdateEventSDto.java, src/main/java/salute/oneshot/domain/event/entity/Event.java, src/main/java/salute/oneshot/domain/event/entity/EventDetail.java, src/main/java/salute/oneshot/domain/event/procssor/EventProcessor.java, src/main/java/salute/oneshot/domain/event/procssor/FreeEventProcessor.java, src/main/java/salute/oneshot/domain/event/procssor/VoteEventProcessor.java, src/main/java/salute/oneshot/domain/event/service/EventService.java
=> feat: Event 수정 기능 추가 #ZU7-130

src/main/java/salute/oneshot/domain/cocktail/controller/CocktailController.java, src/main/java/salute/oneshot/domain/cocktail/service/CocktailService.java, src/main/java/salute/oneshot/domain/ingredient/controller/IngredientController.java, src/main/java/salute/oneshot/domain/ingredient/service/IngredientService.java
#ZU7-96
엘라스틱 서치 조건에 맞는 데이터 개수와 상관없이 최대 10개 반환하는 오류 수정
=> 엘라스틱 서치 최대 반환 개수 수정 #ZU7-96

src/main/java/salute/oneshot/domain/cocktail/controller/CocktailController.java, src/main/java/salute/oneshot/domain/cocktail/service/CocktailScheduler.java, src/main/java/salute/oneshot/domain/cocktail/service/CocktailService.java
=> 조회수 어뷰징 방지 기능 추가 #ZU7-122, #ZU7-129

src/main/java/salute/oneshot/domain/event/controller/AdminEventController.java, src/main/java/salute/oneshot/domain/event/repository/EventRepository.java, src/main/java/salute/oneshot/domain/event/service/EventService.java
=> feat: event 삭제 기능 추가 #ZU7-134

src/main/java/salute/oneshot/domain/auth/controller/AuthViewController.java, src/main/java/salute/oneshot/global/security/SecurityConst.java, src/main/resources/templates/auth/login.html, src/main/resources/templates/auth/signup.html
=> feat: 회원가입 프론트 화면 구현 #ZU7-142

src/main/java/salute/oneshot/global/security/SecurityConst.java
=> fix: buildImgSrcPolicy 의 data 앞에 ; 제거

src/main/java/salute/oneshot/domain/cocktail/controller/CocktailController.java
=> fix: page -> list로 변경

src/docs/asciidoc/address.adoc, src/main/java/salute/oneshot/domain/address/dto/request/CreateAddressRequestDto.java, src/main/resources/static/docs/address.html, src/test/java/salute/oneshot/domain/address/controller/AddressControllerTest.java, src/test/java/salute/oneshot/util/AddressTestFactory.java
=> test: Address 컨트롤러 테스트 추가 #ZU7-153

src/docs/asciidoc/auth.adoc, src/main/java/salute/oneshot/domain/address/entity/Address.java, src/main/java/salute/oneshot/domain/address/service/AddressService.java, src/main/resources/static/docs/address.html, src/main/resources/static/docs/auth.html, src/main/resources/static/docs/index.html, src/test/java/salute/oneshot/domain/address/controller/AddressControllerTest.java, src/test/java/salute/oneshot/domain/auth/controller/AuthControllerTest.java
=> test: Auth, Address 테스트 코드 수정 #ZU7-154

src/docs/asciidoc/address.adoc, src/docs/asciidoc/auth.adoc, src/docs/asciidoc/cocktail.adoc, src/docs/asciidoc/index.adoc, src/test/java/salute/oneshot/config/RestDocsConfiguration.java, src/test/java/salute/oneshot/domain/cocktail/controller/CocktailControllerTest.java, src/test/java/salute/oneshot/domain/common/AbstractRestDocsTests.java, src/test/java/salute/oneshot/util/CocktailTestFactory.java, src/test/java/salute/oneshot/util/IngredientTestFactory.java
=> Test/cocktail/controller #ZU7-156 , #ZU7-157

src/docs/asciidoc/admin-coupon.adoc, src/docs/asciidoc/coupon.adoc, src/main/java/salute/oneshot/domain/coupon/dto/request/CpnRequestDto.java, src/main/java/salute/oneshot/domain/coupon/dto/request/UserCpnRequestDto.java, src/main/java/salute/oneshot/domain/coupon/dto/response/CpnDetailResponseDto.java, src/main/java/salute/oneshot/domain/coupon/entity/Coupon.java, src/main/java/salute/oneshot/domain/coupon/service/CouponService.java, src/main/resources/static/docs/address.html, src/main/resources/static/docs/admin-coupon.html, src/main/resources/static/docs/auth.html, src/main/resources/static/docs/coupon.html, src/main/resources/static/docs/index.html, src/test/java/salute/oneshot/domain/address/controller/AddressControllerTest.java, src/test/java/salute/oneshot/domain/auth/controller/AuthControllerTest.java, src/test/java/salute/oneshot/domain/coupon/controller/AdminCouponControllerTest.java, src/test/java/salute/oneshot/domain/coupon/controller/CouponControllerTest.java, src/test/java/salute/oneshot/util/CouponTestFactory.java
=> test: Coupon 컨트롤러 테스트 코드 추가 #ZU7-159

src/docs/asciidoc/coupon.adoc, src/docs/asciidoc/favorite.adoc, src/docs/asciidoc/index.adoc, src/main/java/salute/oneshot/domain/favorite/controller/FavoriteController.java, src/main/java/salute/oneshot/domain/favorite/dto/response/FavoriteResponseDto.java, src/main/java/salute/oneshot/domain/favorite/entity/Favorite.java, src/main/java/salute/oneshot/domain/favorite/service/FavoriteService.java, src/test/java/salute/oneshot/domain/favorite/controller/FavoriteControllerTest.java, src/test/java/salute/oneshot/util/FavoriteTestFactory.java
=> test: 즐겨찾기 테스트 코드 추가 #ZU7-160

src/main/resources/static/docs/coupon.html, src/main/resources/static/docs/favorite.html, src/main/resources/static/docs/index.html
=> test: restDocs html #ZU7-160

src/docs/asciidoc/admin-user.adoc, src/docs/asciidoc/user-controller.adoc, src/main/java/salute/oneshot/domain/user/dto/repuest/UpdateRoleRequestDto.java, src/main/java/salute/oneshot/domain/user/dto/repuest/UpdateUserRequestDto.java, src/main/java/salute/oneshot/domain/user/dto/response/UserRoleResponseDto.java, src/main/java/salute/oneshot/domain/user/service/UserService.java, src/main/resources/static/docs/address.html, src/main/resources/static/docs/admin-coupon.html, src/main/resources/static/docs/admin-user.html, src/main/resources/static/docs/cocktail.html, src/main/resources/static/docs/coupon.html, src/main/resources/static/docs/index.html, src/main/resources/static/docs/user-controller.html, src/test/java/salute/oneshot/domain/address/controller/AddressControllerTest.java, src/test/java/salute/oneshot/domain/cocktail/controller/CocktailControllerTest.java, src/test/java/salute/oneshot/domain/coupon/controller/AdminCouponControllerTest.java, src/test/java/salute/oneshot/domain/coupon/controller/CouponControllerTest.java, src/test/java/salute/oneshot/domain/user/controller/SuperAdminUserControllerTest.java, src/test/java/salute/oneshot/domain/user/controller/UserControllerTest.java, src/test/java/salute/oneshot/util/AddressTestFactory.java, src/test/java/salute/oneshot/util/CouponTestFactory.java, src/test/java/salute/oneshot/util/UserTestFactory.java
=> test: User 테스트 코드 추가 #ZU7-161

src/main/java/salute/oneshot/domain/banner/controller/AdminBannerController.java, src/main/java/salute/oneshot/domain/banner/controller/BannerController.java, src/main/java/salute/oneshot/domain/banner/dto/request/BannerRequestDto.java, src/main/java/salute/oneshot/domain/banner/dto/response/BannerResponseDto.java, src/main/java/salute/oneshot/domain/banner/service/BannerService.java, src/test/java/salute/oneshot/domain/banner/controller/AdminBannerControllerTest.java, src/test/java/salute/oneshot/domain/banner/controller/BannerControllerTest.java, src/test/java/salute/oneshot/util/BannerTestFactory.java
=> test: Banner controller 테스트코드 추가 #ZU7-167

src/main/java/salute/oneshot/domain/delivery/controller/AdminDeliveryController.java, src/main/java/salute/oneshot/domain/delivery/dto/request/DeliveryRequestDto.java, src/main/java/salute/oneshot/domain/delivery/dto/request/UpdateDeliveryRequestDto.java, src/main/java/salute/oneshot/domain/delivery/dto/service/AdminDeliverySDto.java, src/main/java/salute/oneshot/domain/delivery/dto/service/DeliverySDto.java, src/main/java/salute/oneshot/domain/delivery/entity/Delivery.java, src/main/java/salute/oneshot/domain/delivery/enums/CourierCompany.java, src/main/java/salute/oneshot/domain/delivery/enums/ShippingStatus.java, src/test/java/salute/oneshot/domain/delivery/controller/AdminDeliveryControllerTest.java, src/test/java/salute/oneshot/domain/delivery/controller/DeliveryControllerTest.java, src/test/java/salute/oneshot/util/DeliveryTestFactory.java, src/test/java/salute/oneshot/util/OrderTestFactory.java
=> test: Delivery 컨트롤러 테스트 추가 #ZU7-168

src/test/java/salute/oneshot/config/RestDocsConfiguration.java, src/test/java/salute/oneshot/domain/address/controller/AddressControllerTest.java, src/test/java/salute/oneshot/domain/cocktail/controller/CocktailControllerTest.java, src/test/java/salute/oneshot/domain/common/AbstractRestDocsTests.java
=> Cockail 스웨거 태그 및 파라미터 추가 #ZU7-156

.github/workflows/cd-test.yml, docker-compose-prod.yaml, src/main/java/salute/oneshot/domain/common/facade/OrderPaymentFacade.java, src/main/java/salute/oneshot/domain/payment/controller/PaymentController.java, src/main/java/salute/oneshot/domain/payment/service/PaymentService.java, src/test/java/salute/oneshot/domain/cart/controller/CartControllerTest.java, src/test/java/salute/oneshot/domain/chat/controller/ChatControllerTest.java, src/test/java/salute/oneshot/domain/ingredientReview/controller/IngredientReviewControllerTest.java, src/test/java/salute/oneshot/domain/order/controller/OrderControllerTest.java, src/test/java/salute/oneshot/domain/payment/controller/PaymentControllerTest.java, src/test/java/salute/oneshot/domain/product/controller/ProductControllerTest.java, src/test/java/salute/oneshot/domain/recipeReview/RecipeReviewControllerTest.java, src/test/java/salute/oneshot/util/CartTestFactory.java, src/test/java/salute/oneshot/util/ChatTestFactory.java, src/test/java/salute/oneshot/util/IngredientReviewTestFactory.java, src/test/java/salute/oneshot/util/OrderTestFactory.java, src/test/java/salute/oneshot/util/ProductTestFactory.java, src/test/java/salute/oneshot/util/RecipeReviewTestFactory.java
=> test: PathVariable 처리, 생성자 Reflection, List.of() #ZU7-155

src/test/java/salute/oneshot/domain/ingredientReview/controller/IngredientReviewControllerTest.java
=> test : 재료 리뷰 스웨거 태그 및 파라미터 추가

src/test/java/salute/oneshot/domain/cocktail/controller/CocktailControllerTest.java
=> test : 칵테일 스웨거 파라미터 타입 추가

src/main/java/salute/oneshot/domain/cocktail/controller/CocktailController.java, src/main/java/salute/oneshot/global/util/CookieUtil.java
#ZU7-129
배열로 관리하던 값 문자열로 변경
테스트코드까지 확인함# #️⃣ Kan Board Number
배열로 관리하던 값 문자열로 변경
테스트코드까지 확인함
=> bugFix: 배열로 값 설정으로 인한 오류 수정 #ZU7-129

src/test/java/salute/oneshot/domain/cocktail/controller/CocktailControllerTest.java
=> test : 인기 칵테일 조회 테스트 추가

src/main/java/salute/oneshot/domain/cocktail/controller/CocktailController.java, src/test/java/salute/oneshot/domain/cocktail/controller/CocktailControllerTest.java
=> refactor : 재료 기반 칵테일 검색 수정

src/test/java/salute/oneshot/domain/cocktail/controller/CocktailControllerTest.java
=> test : 재료 기반 칵테일 검색 테스트 수정
